#!/bin/bash
BASEDIR="/opt"
pushd "$BASEDIR"
# install git if not done yet.
apt update
apt install -y git
if [[ ! -d "/opt/mailcow-monobear-addons" ]]; then
	git clone https://github.com/monofox/mailcow-monobear-addons.git
fi
pushd "mailcow-monobear-addons"
git pull

# requirements
python3 setup.py build
python3 setup.py install

# configuration
mkdir -p "configs"
CFGFILE="configs/mbear.yaml"
if [[ ! -z ${REDIS_SLAVEOF_IP} ]]; then
  REDIS_HOST="${REDIS_SLAVEOF_IP}"
  REDIS_PORT=${REDIS_SLAVEOF_PORT}
else
  REDIS_HOST="redis"
  REDIS_PORT=6379
fi
cat <<EOF > $CFGFILE
# Autogenerated by mailcow
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pwd: ""
EOF
popd
popd
