#!/bin/bash
BASEDIR="/opt"
pushd "$BASEDIR"
# install git if not done yet.
apt update
apt install -y git
if [[ ! -d "/opt/mailcow-monobear-addons" ]]; then
	git clone https://github.com/monofox/mailcow-monobear-addons.git
fi
pushd "mailcow-monobear-addons"
git pull

# requirements
python3 setup.py build
python3 setup.py install

# configuration
mkdir -p "configs"
CFGFILE="configs/mbear.yaml"
if [[ ! -z ${REDIS_SLAVEOF_IP} ]]; then
  REDIS_HOST="${REDIS_SLAVEOF_IP}"
  REDIS_PORT=${REDIS_SLAVEOF_PORT}
else
  REDIS_HOST="redis"
  REDIS_PORT=6379
fi
cat <<EOF > $CFGFILE
# Autogenerated by mailcow
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pwd: ""
smtp:
  notify: True
  host: postfix
  port: 587
  tls: True
  verifyCert: False
  sender: noreply@monobear.de
EOF

# update the dovecot sql passdb
sed -i "s/^password_query = SELECT password /password_query = SELECT password, '%w' as userdb_plain_pass /g" /etc/dovecot/sql/dovecot-dict-sql-passdb.conf

# add the login script
cat <<EOF > /etc/dovecot/extra.conf
# have our own login
service imap-postlogin {
  executable = script-login /usr/local/bin/postlogin.sh /opt/mailcow-monobear-addons/bin/testPasswordLogin.sh
  unix_listener imap-postlogin {
    user = vmail
    mode = 0660
  }
}
# storage is on network storage
mmap_disable = yes
mail_fsync = always
mail_nfs_index = yes
mail_nfs_storage = yes
EOF

popd
popd
