#!/bin/sh
BASEDIR=$(dirname "$0")
pushd $BASEDIR

# requirements
python3 setup.py build
python3 setup.py install --user 

# configuration
BASEDIR=$(dirname "$0")
mkdir -p "$BASEDIR/configs"
CFGFILE="$BASEDIR/configs/mbear.yaml"
if [[ ! -z ${REDIS_SLAVEOF_IP} ]]; then
  REDIS_HOST="${REDIS_SLAVEOF_IP}"
  REDIS_PORT=${REDIS_SLAVEOF_PORT}
else
  REDIS_HOST="redis"
  REDIS_PORT=6379
fi
cat <<EOF > $CFGFILE
# Autogenerated by mailcow
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pwd: ""
EOF

popd
